kind: PersistentVolume
apiVersion: v1
metadata:
  name: log-persistent-volume-ashish
  namespace: ashish
  labels:
    type: local
spec:
  volumeMode: Filesystem
  storageClassName: pv-ashish
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/logs-ashish"
