apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-persistent-claim-ashish
  namespace: ashish
spec:
  volumeMode: Filesystem
  storageClassName: pv-ashish
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
