apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-persistent-claim
spec:
  volumeMode: Filesystem
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi