apiVersion: v1
kind: Pod
metadata:
  labels:
    app: business
  name: business
spec:
  volumes:
  - name: log-volume
    persistentVolumeClaim:
      claimName: log-persistent-claim
  containers:
  - image: adityapratapbhuyan/business:distributed
    imagePullPolicy: Always
    name: business
    volumeMounts:
      - name: log-volume
        mountPath: "/var/tmp/"
    ports:
    - containerPort: 8081
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
