kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-persistent-volume-<your-name>
  namespace: aditya
  labels:
    type: local
spec:
  storageClassName: mysql-aditya
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data-<your-name>"
