kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-persistent-volume-ashish
  namespace: ashish
  labels:
    type: local
spec:
  storageClassName: mysql-ashish
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data-ashish"
