apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-ashish
  namespace: ashish
spec:
  storageClassName: mysql-ashish
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
